# Generated by Django 4.1.3 on 2022-11-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_proyecto_final', '0005_rename_t_almacen_id_detalletemperatura_almacen_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='clave',
            field=models.CharField(default='', max_length=200),
        ),
    ]
