# Generated by Django 4.1.3 on 2022-11-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_proyecto_final', '0006_usuario_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='imagen',
            field=models.CharField(default='', max_length=200),
        ),
    ]
