# Generated by Django 4.1.3 on 2022-11-30 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_proyecto_final', '0008_remove_usuario_cargo_id_delete_cargos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epp',
            name='almacen_id',
        ),
    ]
